numbers = [5, 2, 1, 7, 4, 4]
print(numbers)
numbers.append(20)
print(numbers)
numbers.insert(0, 10)
print(numbers)
numbers.remove(5)
print(numbers)
numbers.pop()
print(numbers)
print(numbers.index(4))
print(5 in numbers)
print(numbers.count(4))
numbers.sort()
numbers.reverse()
print(numbers)
numbers2 =numbers.copy()
print(numbers2)
numbers.clear()
print(numbers)